### ISSUE TITLE
请问您可以提供一下数据集嘛

### ISSUE THREAD

**Issue by upupbo** [zzzqzhou/2020-National-Artificial-Intelligence-Challenge_Remote-Sense#1]
请问您可以提供一下数据集嘛

**Comment by zzzqzhou** [comment]
你好，我已上传初赛训练及测试数据至百度网盘https://pan.baidu.com/s/1UHrvfONZiyVO8e2BJZdEfA，提取码：gg7y。
请勿用于商业用途，非盈利用途请注明出处https://naic.pcl.ac.cn/contest/8/track/29/stage/30/problem/51。

**Comment by upupbo** [comment]
可以提供一下复赛数据集嘛

**Comment by zzzqzhou** [comment]
抱歉，复赛数据下载通道已关闭，之前的数据被我清理了。
